# Site settings
title: Zewei Xiong
email: z.xiong@gsi.de
description: Academic and official webpage of Dr. Zewei Xiong
baseurl: "https://zeweixiong.github.io"
url: ""

# Google analytics ID: Uncomment and your own, if you like
# google_analytics: XX
google_analytics_4: G-H6HEPJ41K9
# google_tag_manager: XXX

# Footer info
contact: >
  Zewei Xiong<br/>
  Postdoctoral Researcher<br/>
  GSI Helmholtzzentrum für Schwerionenforschung<br/>
  Planckstraße 1<br/>
  64291 Darmstadt, Germany

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Pages shown in navbar
nav_pages:
  - name: about
  - name: publications
  - name: talks
  - name: blog

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links
  syntax_highlighter: rouge

plugins: ["jekyll/scholar"]

scholar:
  last_name: Xiong
  first_name: [Zewei]

  style: citesty
  locale: en

  source: /assets/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
